### ISSUE TITLE
Include Module Registration doesn't work on the very first visit

### ISSUE THREAD

**Issue by robert-cardillo** [michielgerritsen/magento2-model-generator#325]
Hello again.

While using the app with Chrome 109.0.5414.75 (64 bit) I encountered an issue where checking or unchecking Include Module Registration checkbox has no effect. It only happens on the very first visit of the app and refreshing solves the problem, so this is a very negligable issue to be honest, but here are the steps to produce it:

1. Open the app
2. Clear the Local Storage from Chrome Dev Tools (so that we can re-create the first visit experience)
3. Refresh the page
4. Fill out Vendor, Module and Model Name inputs
5. (Treeview is generated)
6. Check the Include Module Registration checkbox
7. `module.xml` and `registration.php` files are not included in the treeview.

![image](https://user-images.githubusercontent.com/1337570/213197379-ebeca4cb-d231-4a5f-8ae0-10d260c77eb7.png)

**Comment by michielgerritsen** [comment]
Nice catch! Thanks!
